// Code generated by mockery v2.52.2. DO NOT EDIT.

package domain

import (
	context "context"

	domain "github.com/Kryniol/go-moniepoint-storage-engine/domain"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockRangeIndex is an autogenerated mock type for the RangeIndex type
type MockRangeIndex struct {
	mock.Mock
}

// Add provides a mock function with given fields: ctx, entry
func (_m *MockRangeIndex) Add(ctx context.Context, entry domain.IndexEntry) error {
	ret := _m.Called(ctx, entry)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.IndexEntry) error); ok {
		r0 = rf(ctx, entry)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindFirst provides a mock function with given fields: ctx
func (_m *MockRangeIndex) FindFirst(ctx context.Context) (*domain.IndexEntry, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindFirst")
	}

	var r0 *domain.IndexEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*domain.IndexEntry, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *domain.IndexEntry); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.IndexEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindLast provides a mock function with given fields: ctx
func (_m *MockRangeIndex) FindLast(ctx context.Context) (*domain.IndexEntry, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindLast")
	}

	var r0 *domain.IndexEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*domain.IndexEntry, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *domain.IndexEntry); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.IndexEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindRange provides a mock function with given fields: ctx, start, end
func (_m *MockRangeIndex) FindRange(ctx context.Context, start domain.IndexEntry, end domain.IndexEntry) (map[string]domain.IndexEntry, error) {
	ret := _m.Called(ctx, start, end)

	if len(ret) == 0 {
		panic("no return value specified for FindRange")
	}

	var r0 map[string]domain.IndexEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.IndexEntry, domain.IndexEntry) (map[string]domain.IndexEntry, error)); ok {
		return rf(ctx, start, end)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.IndexEntry, domain.IndexEntry) map[string]domain.IndexEntry); ok {
		r0 = rf(ctx, start, end)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]domain.IndexEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.IndexEntry, domain.IndexEntry) error); ok {
		r1 = rf(ctx, start, end)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindSince provides a mock function with given fields: ctx, since
func (_m *MockRangeIndex) FindSince(ctx context.Context, since time.Time) (map[string]domain.IndexEntry, error) {
	ret := _m.Called(ctx, since)

	if len(ret) == 0 {
		panic("no return value specified for FindSince")
	}

	var r0 map[string]domain.IndexEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) (map[string]domain.IndexEntry, error)); ok {
		return rf(ctx, since)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) map[string]domain.IndexEntry); ok {
		r0 = rf(ctx, since)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]domain.IndexEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, since)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockRangeIndex creates a new instance of MockRangeIndex. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRangeIndex(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRangeIndex {
	mock := &MockRangeIndex{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
