// Code generated by mockery v2.52.2. DO NOT EDIT.

package domain

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockWriteStorage is an autogenerated mock type for the WriteStorage type
type MockWriteStorage struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, key
func (_m *MockWriteStorage) Delete(ctx context.Context, key string) error {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Set provides a mock function with given fields: ctx, key, data
func (_m *MockWriteStorage) Set(ctx context.Context, key string, data []byte) error {
	ret := _m.Called(ctx, key, data)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) error); ok {
		r0 = rf(ctx, key, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockWriteStorage creates a new instance of MockWriteStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWriteStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWriteStorage {
	mock := &MockWriteStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
