// Code generated by mockery v2.52.2. DO NOT EDIT.

package domain

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockReplicaSync is an autogenerated mock type for the ReplicaSync type
type MockReplicaSync struct {
	mock.Mock
}

// SyncFromLeader provides a mock function with given fields: ctx
func (_m *MockReplicaSync) SyncFromLeader(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SyncFromLeader")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockReplicaSync creates a new instance of MockReplicaSync. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReplicaSync(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReplicaSync {
	mock := &MockReplicaSync{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
